[package]
name = "bevy-entity-relations-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]

[dependencies]
naia-bevy-shared = { path = "../../../naia/adapters/bevy/shared" }
bevy_ecs = { version = "0.12.1", default-features=false}
cfg-if = { version = "1.0" }
log = { version = "0.4" }